
package com.vidyo.admin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "VidyoPortalAdminServicePortType", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VidyoPortalAdminServicePortType {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetMembersResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getMembers")
    @WebResult(name = "GetMembersResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetMembersResponse getMembers(
        @WebParam(name = "GetMembersRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetMembersRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetMemberResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws MemberNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getMember")
    @WebResult(name = "GetMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetMemberResponse getMember(
        @WebParam(name = "GetMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetMemberRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, MemberNotFoundFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.AddMemberResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws MemberAlreadyExistsFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "addMember")
    @WebResult(name = "AddMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public AddMemberResponse addMember(
        @WebParam(name = "AddMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        AddMemberRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, MemberAlreadyExistsFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.UpdateMemberResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws MemberNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "updateMember")
    @WebResult(name = "UpdateMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public UpdateMemberResponse updateMember(
        @WebParam(name = "UpdateMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        UpdateMemberRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, MemberNotFoundFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.DeleteMemberResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws MemberNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "deleteMember")
    @WebResult(name = "DeleteMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DeleteMemberResponse deleteMember(
        @WebParam(name = "DeleteMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DeleteMemberRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, MemberNotFoundFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetRoomsResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRooms")
    @WebResult(name = "GetRoomsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRoomsResponse getRooms(
        @WebParam(name = "GetRoomsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetRoomsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetRoomResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws RoomNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRoom")
    @WebResult(name = "GetRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRoomResponse getRoom(
        @WebParam(name = "GetRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.AddRoomResponse
     * @throws RoomAlreadyExistsFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "addRoom")
    @WebResult(name = "AddRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public AddRoomResponse addRoom(
        @WebParam(name = "AddRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        AddRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomAlreadyExistsFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.UpdateRoomResponse
     * @throws RoomAlreadyExistsFault_Exception
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws RoomNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "updateRoom")
    @WebResult(name = "UpdateRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public UpdateRoomResponse updateRoom(
        @WebParam(name = "UpdateRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        UpdateRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomAlreadyExistsFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.DeleteRoomResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws RoomNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "deleteRoom")
    @WebResult(name = "DeleteRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DeleteRoomResponse deleteRoom(
        @WebParam(name = "DeleteRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DeleteRoomRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, RoomNotFoundFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetGroupsResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getGroups")
    @WebResult(name = "GetGroupsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetGroupsResponse getGroups(
        @WebParam(name = "GetGroupsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetGroupsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetGroupResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GroupNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getGroup")
    @WebResult(name = "GetGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetGroupResponse getGroup(
        @WebParam(name = "GetGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetGroupRequest parameter)
        throws GeneralFault_Exception, GroupNotFoundFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.AddGroupResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GroupAlreadyExistsFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "addGroup")
    @WebResult(name = "AddGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public AddGroupResponse addGroup(
        @WebParam(name = "AddGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        AddGroupRequest parameter)
        throws GeneralFault_Exception, GroupAlreadyExistsFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.UpdateGroupResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GroupNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "updateGroup")
    @WebResult(name = "UpdateGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public UpdateGroupResponse updateGroup(
        @WebParam(name = "UpdateGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        UpdateGroupRequest parameter)
        throws GeneralFault_Exception, GroupNotFoundFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.DeleteGroupResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GroupNotFoundFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "deleteGroup")
    @WebResult(name = "DeleteGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public DeleteGroupResponse deleteGroup(
        @WebParam(name = "DeleteGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        DeleteGroupRequest parameter)
        throws GeneralFault_Exception, GroupNotFoundFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetParticipantsResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getParticipants")
    @WebResult(name = "GetParticipantsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetParticipantsResponse getParticipants(
        @WebParam(name = "GetParticipantsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetParticipantsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.InviteToConferenceResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "inviteToConference")
    @WebResult(name = "InviteToConferenceResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public InviteToConferenceResponse inviteToConference(
        @WebParam(name = "InviteToConferenceRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        InviteToConferenceRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.LeaveConferenceResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "leaveConference")
    @WebResult(name = "LeaveConferenceResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public LeaveConferenceResponse leaveConference(
        @WebParam(name = "LeaveConferenceRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        LeaveConferenceRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.MuteAudioResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "muteAudio")
    @WebResult(name = "MuteAudioResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public MuteAudioResponse muteAudio(
        @WebParam(name = "MuteAudioRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        MuteAudioRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.UnmuteAudioResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "unmuteAudio")
    @WebResult(name = "UnmuteAudioResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public UnmuteAudioResponse unmuteAudio(
        @WebParam(name = "UnmuteAudioRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        UnmuteAudioRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.StartVideoResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "startVideo")
    @WebResult(name = "StartVideoResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StartVideoResponse startVideo(
        @WebParam(name = "StartVideoRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StartVideoRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.StopVideoResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "stopVideo")
    @WebResult(name = "StopVideoResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StopVideoResponse stopVideo(
        @WebParam(name = "StopVideoRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StopVideoRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.CreateRoomURLResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createRoomURL")
    @WebResult(name = "CreateRoomURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateRoomURLResponse createRoomURL(
        @WebParam(name = "CreateRoomURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateRoomURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.RemoveRoomURLResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeRoomURL")
    @WebResult(name = "RemoveRoomURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveRoomURLResponse removeRoomURL(
        @WebParam(name = "RemoveRoomURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveRoomURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.CreateRoomPINResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createRoomPIN")
    @WebResult(name = "CreateRoomPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateRoomPINResponse createRoomPIN(
        @WebParam(name = "CreateRoomPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateRoomPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.RemoveRoomPINResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeRoomPIN")
    @WebResult(name = "RemoveRoomPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveRoomPINResponse removeRoomPIN(
        @WebParam(name = "RemoveRoomPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveRoomPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetLicenseDataResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getLicenseData")
    @WebResult(name = "GetLicenseDataResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetLicenseDataResponse getLicenseData(
        @WebParam(name = "GetLicenseDataRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetLicenseDataRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetPortalVersionResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getPortalVersion")
    @WebResult(name = "GetPortalVersionResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetPortalVersionResponse getPortalVersion(
        @WebParam(name = "GetPortalVersionRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetRecordingProfilesResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRecordingProfiles")
    @WebResult(name = "GetRecordingProfilesResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRecordingProfilesResponse getRecordingProfiles(
        @WebParam(name = "GetRecordingProfilesRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.StartRecordingResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws ResourceNotAvailableFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "startRecording")
    @WebResult(name = "StartRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StartRecordingResponse startRecording(
        @WebParam(name = "StartRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StartRecordingRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception, ResourceNotAvailableFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.PauseRecordingResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "pauseRecording")
    @WebResult(name = "PauseRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public PauseRecordingResponse pauseRecording(
        @WebParam(name = "PauseRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        PauseRecordingRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.ResumeRecordingResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "resumeRecording")
    @WebResult(name = "ResumeRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public ResumeRecordingResponse resumeRecording(
        @WebParam(name = "ResumeRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        ResumeRecordingRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.StopRecordingResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "stopRecording")
    @WebResult(name = "StopRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public StopRecordingResponse stopRecording(
        @WebParam(name = "StopRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        StopRecordingRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetLocationTagsResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getLocationTags")
    @WebResult(name = "GetLocationTagsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetLocationTagsResponse getLocationTags(
        @WebParam(name = "GetLocationTagsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetLocationTagsRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetWebcastURLResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getWebcastURL")
    @WebResult(name = "GetWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetWebcastURLResponse getWebcastURL(
        @WebParam(name = "GetWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.CreateWebcastURLResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createWebcastURL")
    @WebResult(name = "CreateWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateWebcastURLResponse createWebcastURL(
        @WebParam(name = "CreateWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.RemoveWebcastURLResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeWebcastURL")
    @WebResult(name = "RemoveWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveWebcastURLResponse removeWebcastURL(
        @WebParam(name = "RemoveWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveWebcastURLRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.CreateWebcastPINResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createWebcastPIN")
    @WebResult(name = "CreateWebcastPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateWebcastPINResponse createWebcastPIN(
        @WebParam(name = "CreateWebcastPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateWebcastPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.RemoveWebcastPINResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeWebcastPIN")
    @WebResult(name = "RemoveWebcastPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveWebcastPINResponse removeWebcastPIN(
        @WebParam(name = "RemoveWebcastPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveWebcastPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetRoomProfilesResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRoomProfiles")
    @WebResult(name = "GetRoomProfilesResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRoomProfilesResponse getRoomProfiles(
        @WebParam(name = "GetRoomProfilesRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        Object parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.GetRoomProfileResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "getRoomProfile")
    @WebResult(name = "GetRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public GetRoomProfileResponse getRoomProfile(
        @WebParam(name = "GetRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        GetRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.SetRoomProfileResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "setRoomProfile")
    @WebResult(name = "SetRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public SetRoomProfileResponse setRoomProfile(
        @WebParam(name = "SetRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        SetRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.RemoveRoomProfileResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeRoomProfile")
    @WebResult(name = "RemoveRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveRoomProfileResponse removeRoomProfile(
        @WebParam(name = "RemoveRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveRoomProfileRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.CreateModeratorPINResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws InvalidModeratorPINFormatFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "createRoomModeratorPIN")
    @WebResult(name = "CreateModeratorPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public CreateModeratorPINResponse createModeratorPIN(
        @WebParam(name = "CreateModeratorPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        CreateModeratorPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, InvalidModeratorPINFormatFault_Exception, NotLicensedFault_Exception
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns com.vidyo.admin.RemoveModeratorPINResponse
     * @throws InvalidArgumentFault_Exception
     * @throws NotLicensedFault_Exception
     * @throws GeneralFault_Exception
     */
    @WebMethod(action = "removeRoomModeratorPIN")
    @WebResult(name = "RemoveModeratorPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    public RemoveModeratorPINResponse removeModeratorPIN(
        @WebParam(name = "RemoveModeratorPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
        RemoveModeratorPINRequest parameter)
        throws GeneralFault_Exception, InvalidArgumentFault_Exception, NotLicensedFault_Exception
    ;

}
