
package com.vidyo.admin;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VidyoPortalAdminService", targetNamespace = "http://portal.vidyo.com/admin/v1_1", wsdlLocation = "http://jivesoftware.sandbox.vidyo.com/services/v1_1/VidyoPortalAdminService?wsdl")
public class VidyoPortalAdminService
    extends Service
{

    private final static URL VIDYOPORTALADMINSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.vidyo.admin.VidyoPortalAdminService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.vidyo.admin.VidyoPortalAdminService.class.getResource(".");
            url = new URL(baseUrl, "http://jivesoftware.sandbox.vidyo.com/services/v1_1/VidyoPortalAdminService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://jivesoftware.sandbox.vidyo.com/services/v1_1/VidyoPortalAdminService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VIDYOPORTALADMINSERVICE_WSDL_LOCATION = url;
    }

    public VidyoPortalAdminService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VidyoPortalAdminService() {
        super(VIDYOPORTALADMINSERVICE_WSDL_LOCATION, new QName("http://portal.vidyo.com/admin/v1_1", "VidyoPortalAdminService"));
    }

    /**
     * 
     * @return
     *     returns VidyoPortalAdminServicePortType
     */
    @WebEndpoint(name = "VidyoPortalAdminServicePort")
    public VidyoPortalAdminServicePortType getVidyoPortalAdminServicePort() {
        return super.getPort(new QName("http://portal.vidyo.com/admin/v1_1", "VidyoPortalAdminServicePort"), VidyoPortalAdminServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VidyoPortalAdminServicePortType
     */
    @WebEndpoint(name = "VidyoPortalAdminServicePort")
    public VidyoPortalAdminServicePortType getVidyoPortalAdminServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://portal.vidyo.com/admin/v1_1", "VidyoPortalAdminServicePort"), VidyoPortalAdminServicePortType.class, features);
    }

}
